# Generated by Django 4.0.5 on 2022-06-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_no', models.IntegerField()),
                ('d_email', models.TextField()),
                ('team_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('ec_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ec_email', models.TextField()),
                ('address', models.TextField()),
                ('session', models.DateField()),
                ('linkdin_id', models.TextField()),
            ],
            options={
                'db_table': 'ec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_no', models.TextField()),
                ('m_email', models.TextField()),
                ('username', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('donor_id', models.TextField(primary_key=True, serialize=False)),
                ('payment_month', models.IntegerField(blank=True, null=True)),
                ('payment_year', models.IntegerField(blank=True, null=True)),
                ('payments', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.donor')),
                ('payment_month', models.IntegerField(blank=True, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.member')),
            ],
            options={
                'db_table': 'head',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('sub_head', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.member')),
            ],
            options={
                'db_table': 'sub_head',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.member')),
            ],
            options={
                'db_table': 'volunteer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_no', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('username', models.TextField(blank=True, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.CharField(default=0, max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonorAssignment',
            fields=[
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.volunteer')),
            ],
            options={
                'db_table': 'donor_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('sub_head', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pt_auth.subhead')),
            ],
            options={
                'db_table': 'volunteer_assignment',
                'managed': False,
            },
        ),
    ]
